
name: RunJmeterTests

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run JMeter Tests
        run: mkdir reports
      
      - name: JMeter Test
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: ./TestPlans/S01_SimpleExample/S01_SimpleExample.jmx
          args: "-e -o ./reports/html/"
          
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: result.jtl
          if-no-files-found: error
      
      - name: Upload HTML Reports
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-html-reports
          path: reports
          if-no-files-found: error
                      
